  export const restaurantList=[
    {
      "id": 1,
      "name": "Saffron Spice",
      "cuisines": "Indian, Thai,Punjabi",
      "rating": 4.6,
      "area": "Downtown",
      "city": "Mumbai",
      "avg_rating": 4.5,
      "menu": "Palak Paneer,Chicken Biryani,Garlic Naan,Chole Bhature,Samosa,Aloo Gobi,Rogan Josh,Dal Tadka,",
      "lastMileTravelString": 4.2,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/a5qdifp3dp9o3osqs1n8"
    },
    {
      "id": 2,
      "name": "Taj Tandoor",
      "cuisines": "Indian, Street Food",
      "rating": 4.2,
      "area": "Midtown",
      "city": "Delhi",
      "avg_rating": 4.1,
      "menu": "Paneer Tikka,Vegetable Biryani,Roti,Pulao Rice,Rasmalai,Pakora,Kadai Paneer,Aloo Paratha,",
      "lastMileTravelString": 5.8,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/pd58tuljh1jskcucwnqq"
    },
    {
      "id": 3,
      "name": "Curry King",
      "cuisines": "Indian, South Indian",
      "rating": 4.5,
      "area": "Uptown",
      "city": "Bangalore",
      "avg_rating": 4.3,
      "menu": "Saag Paneer,Tandoori Chicken,Paratha,Pulao Rice,Gulab Jamun,Papadum,Chana Masala,Masoor Dal,",
      "lastMileTravelString": 9.3,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_366/hnx9nazpxdpqpypjo8ld"
    },
    {
      "id": 4,
      "name": "Flavors of India",
      "cuisines": "Indian, Punjabi",
      "rating": 4.4,
      "area": "Chinatown",
      "city": "Kolkata",
      "avg_rating": 4.2,
      "menu": "Paneer Butter Masala,Bhindi Masala,Chapati,Raita,Pulao,Papdi Chaat,Kheer,Malai Kofta,",
      "lastMileTravelString": 5.2,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_366/69a061b7e0f951cef2b4947946f94ec6"
    },
    {
      "id": 5,
      "name": "Spice Valley",
      "cuisines": "Indian, Rajasthani",
      "rating": 4.3,
      "area": "Downtown",
      "city": "Chennai",
      "avg_rating": 4.1,
      "menu": "Dal Tadka,Shahi Paneer,Puri,Chana Dal,Ras Malai,Pakora,Rajma,Aloo Paratha,",
      "lastMileTravelString": 5.8,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/ipliaq089ydejf9y5b57"
    },
    {
      "id": 6,
      "name": "Royal Rasoi",
      "cuisines": "Indian,Thai,italian",
      "rating": 4.7,
      "area": "Hollywood",
      "city": "Hyderabad",
      "avg_rating": 4.6,
      "menu": "Vegetable Biryani,Aloo Gobi,Roti,Pulao Rice,Gulab Jamun,Papadum,Masoor Dal,Vegetable Korma,",
      "lastMileTravelString": 1.1,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/gsu0c2xeycykywavsgny"
    },
    {
      "id": 7,
      "name": "Mirchi Masala",
      "cuisines": "Indian,French,Punjabi",
      "rating": 4.1,
      "area": "Chinatown",
      "city": "Jaipur",
      "avg_rating": 3.9,
      "menu": "Chole Bhature,Matar Paneer,Kulcha,Jeera Rice,Rasmalai,Samosa Chaat,Kadai Paneer,Veg Biryani,",
      "lastMileTravelString": 2.3,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/gsu0c2xeycykywavsgny"
    },
    {
      "id": 8,
      "name": "Masala Masti",
      "cuisines": "Indian,American,Punjabi",
      "rating": 4.6,
      "area": "Little India",
      "city": "Pune",
      "avg_rating": 4.5,
      "menu": "Baingan Bharta,Pav Bhaji,Pulao Rice,Butter Naan,Gajar Halwa,Paneer Tikka,Aloo Paratha,Mango Lassi,",
      "lastMileTravelString": 5.2,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/7d06c2081fdc2bd0101ce2619c499040"
    },
    {
      "id": 9,
      "name": "Zaika Indian Kitchen",
      "cuisines": "Indian,swedish, Greek,Chinese",
      "rating": 4.3,
      "area": "Downtown",
      "city": "Ahmedabad",
      "avg_rating": 4.2,
      "menu": "Paneer Butter Masala,Biryani,Kathi Roll,Tandoori Roti,Rasgulla,Chicken Tikka,Samosa,Raita,",
      "lastMileTravelString": 5.4,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/accfba0e06b352f9fc06bf92db550b2b"
    },
    {
      "id": 10,
      "name": "Pune Spice Junction",
      "cuisines": "Indian,Chinese",
      "rating": 4.4,
      "area": "Midtown",
      "city": "Pune",
      "avg_rating": 4.2,
      "menu": "Misal Pav,Vada Pav,Pani Puri,Sev Puri,Bhel Puri,Dabeli,Kanda Poha,Masala Chai,",
      "lastMileTravelString": 9.9,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/g7fjscuwe99xx0jxvwch"
    },
    {
      "id": 11,
      "name": "Zaika Express",
      "cuisines": "Indian,Greek,Rajasthani",
      "rating": 4.4,
      "area": "Downtown",
      "city": "Chandigarh",
      "avg_rating": 4.2,
      "menu": "Butter Chicken,Palak Paneer,Garlic Naan,Veg Biryani,Samosa,Aloo Gobi,Rogan Josh,Chana Masala,",
      "lastMileTravelString": 10.2,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/zhqxolamkplc0c0m5zps"
    },
    {
      "id": 12,
      "name": "Masala Magic",
      "cuisines": "Indian,Mexican",
      "rating": 4.3,
      "area": "Midtown",
      "city": "Kochi",
      "avg_rating": 4.1,
      "menu": "Paneer Tikka,Veg Pulao,Paratha,Pulao Rice,Gulab Jamun,Pakora,Dal Makhani,Chole Bhature,",
      "lastMileTravelString": 5.3,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/nbc0lqvdiv6z9nd1jrps"
    },
    {
      "id": 13,
      "name": "Sagar Sweets",
      "cuisines": "Indian,Thai,italian",
      "rating": 4.7,
      "area": "Uptown",
      "city": "Amritsar",
      "avg_rating": 4.5,
      "menu": "Aloo Paratha,Kadhi Pakoda,Pav Bhaji,Roti,Rasgulla,Papadum,Paneer Butter Masala,Dosa,",
      "lastMileTravelString": 1.2,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/middy53tmi2ory4hbvgd"
    },
    {
      "id": 14,
      "name": "Chutney Chawal",
      "cuisines": "Indian,Swedish",
      "rating": 4.6,
      "area": "Chinatown",
      "city": "Varanasi",
      "avg_rating": 4.4,
      "menu": "Matar Paneer,Kulcha,Jeera Rice,Butter Chicken,Raita,Samosa,Tandoori Chicken,Pulao Rice,",
      "lastMileTravelString": 1,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/dwyug7gmy0wmohkbxkiu"
    },
    {
      "id": 15,
      "name": "Nawabi Delights",
      "cuisines": "Indian,French,Punjabi",
      "rating": 4.2,
      "area": "Downtown",
      "city": "Jaipur",
      "avg_rating": 4,
      "menu": "Dal Tadka,Paneer Butter Masala,Roti,Pulao Rice,Ras Malai,Pakora,Chana Masala,Aloo Paratha,",
      "lastMileTravelString": 20.3,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/vdl4gydiw7jfjb6aqngj"
    },
    {
      "id": 16,
      "name": "Bawarchi Biryani",
      "cuisines": "Indian,Chinese",
      "rating": 4.8,
      "area": "Hollywood",
      "city": "Hyderabad",
      "avg_rating": 4.6,
      "menu": "Chicken Dum Biryani,Veg Biryani,Chicken 65,Gulab Jamun,Mirchi Bajji,Fish Fry,Paneer Butter Masala,Gobi Manchurian,",
      "lastMileTravelString": 9.1,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/vrm2cwqn9on15nk1bnru"
    },
    {
      "id": 17,
      "name": "Tandoori Flames",
      "cuisines": "Indian, Street Food",
      "rating": 4.1,
      "area": "Chinatown",
      "city": "Amritsar",
      "avg_rating": 3.9,
      "menu": "Paneer Tikka,Chicken Tikka Masala,Butter Naan,Raita,Pulao Rice,Pakora,Chole Bhature,Rasgulla,",
      "lastMileTravelString": 3.3,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/wvfnqby1jsgwsqlnrmcd"
    },
    {
      "id": 18,
      "name": "Chapati Chat",
      "cuisines": "Indian, Greek,Rajasthani",
      "rating": 4.5,
      "area": "Little India",
      "city": "Bangalore",
      "avg_rating": 4.4,
      "menu": "Pani Puri,Pav Bhaji,Bhel Puri,Pulao Rice,Rasgulla,Vada Pav,Misal Pav,Kadai Paneer,",
      "lastMileTravelString": 3.5,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_400/yhrz8rprmygzhq9edjjb"
    },
    {
      "id": 19,
      "name": "Shahi Khana",
      "cuisines": "Indian,American,Sweden",
      "rating": 4.4,
      "area": "North End",
      "city": "Lucknow",
      "avg_rating": 4.2,
      "menu": "Paneer Butter Masala,Vegetable Biryani,Garlic Naan,Pulao Rice,Gajar Halwa,Chole Bhature,Aloo Paratha,Ras Malai,",
      "lastMileTravelString": 8.2,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_366/RX_THUMBNAIL/IMAGES/VENDOR/2024/4/1/3770fd3f-18e3-4a61-b8df-8a36fd7d5887_457522.jpg"
    },
    {
      "id": 20,
      "name": "Chennai Chettinad",
      "cuisines": "Indian,French,Punjabi",
      "rating": 4.6,
      "area": "Little India",
      "city": "Chennai",
      "avg_rating": 4.4,
      "menu": "Chettinad Fish Curry,Chettinad Paneer,Chettinad Mutton,Chettinad Veg Curry,Paniyaram,Kothu Parotta,Idiyappam,Appam,",
      "lastMileTravelString": 8.4,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_244,h_328/v1677873155/portal/m/Food_mweb_1.png"
    },
    {
      "id": 21,
      "name": "Delhi Darbar",
      "cuisines": "Indian,Chinese,Swedish",
      "rating": 4.6,
      "area": "Uptown",
      "city": "Delhi",
      "avg_rating": 4.5,
      "menu": "Butter Chicken,Paneer Tikka Masala,Naan,Biryani,Samosa,Aloo Gobi,Dal Makhani,Chole Bhature,",
      "lastMileTravelString": 9.4,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_366/c99751d54e4e1847186c62b3309c1327"
    },
    {
      "id": 22,
      "name": "Spice Palace",
      "cuisines": "Indian,Italian,Rajasthani",
      "rating": 4.4,
      "area": "Chinatown",
      "city": "Mumbai",
      "avg_rating": 4.2,
      "menu": "Palak Paneer,Chicken Biryani,Garlic Naan,Masoor Dal,Ras Malai,Pakora,Kadai Paneer,Aloo Paratha,",
      "lastMileTravelString": 4.4,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_366/6e04be27387483a7c00444f8e8241108"
    },
    {
      "id": 23,
      "name": "Punjabi Tadka",
      "cuisines": "Indian,Italian, Swedish",
      "rating": 4.7,
      "area": "Downtown",
      "city": "Amritsar",
      "avg_rating": 4.6,
      "menu": "Vegetable Biryani,Aloo Gobi,Roti,Pulao Rice,Gulab Jamun,Papadum,Chicken Tikka Masala,Tandoori Chicken,",
      "lastMileTravelString": 5.5,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_366/hnx9nazpxdpqpypjo8ld"
    },
    {
      "id": 24,
      "name": "Chandni Chowk",
      "cuisines": "Indian,American,Punjabi",
      "rating": 4.1,
      "area": "Midtown",
      "city": "Delhi",
      "avg_rating": 3.9,
      "menu": "Chole Bhature,Matar Paneer,Kulcha,Jeera Rice,Rasmalai,Samosa Chaat,Kadai Paneer,Veg Biryani,",
      "lastMileTravelString": 1.1,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/e87arla0ikdefb9b1soq"
    },
    {
      "id": 25,
      "name": "Rajasthani Rasoi",
      "cuisines": "Indian,Nepali",
      "rating": 4.5,
      "area": "Little India",
      "city": "Jaipur",
      "avg_rating": 4.4,
      "menu": "Laal Maas,Gatte Ki Sabzi,Missi Roti,Bajre Ki Roti,Moong Dal Halwa,Ghevar,Gujia,Kalmi Vada,",
      "lastMileTravelString": 2.2,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/tdtupomvpsmmscvxzqq0"
    },
    {
      "id": 26,
      "name": "Pind Punjabi Dhaba",
      "cuisines": "Indian,Swedish, Greek",
      "rating": 4.3,
      "area": "North End",
      "city": "Amritsar",
      "avg_rating": 4.2,
      "menu": "Makki Di Roti,Paneer Tikka,Dal Tadka,Pulao Rice,Gulab Jamun,Pakora,Chole Bhature,Aloo Paratha,",
      "lastMileTravelString": 3.3,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/c3c1b7ebf9cb4986310b05555b5f4072"
    },
    {
      "id": 27,
      "name": "Mumbai Masala",
      "cuisines": "Indian,Assamese,Punjabi",
      "rating": 4.6,
      "area": "Chinatown",
      "city": "Mumbai",
      "avg_rating": 4.5,
      "menu": "Pav Bhaji,Misal Pav,Pani Puri,Sev Puri,Bhel Puri,Dabeli,Kulfi,Pav Bhaji,",
      "lastMileTravelString": 5.5,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/zqmgprfrwvr6cnjruubo"
    },
    {
      "id": 28,
      "name": "Kolkata Kathi Rolls",
      "cuisines": "Indian,Italian,Rajasthani",
      "rating": 4.2,
      "area": "Downtown",
      "city": "Kolkata",
      "avg_rating": 4,
      "menu": "Egg Kathi Roll,Paneer Kathi Roll,Aloo Kathi Roll,Mutton Kathi Roll,Fish Kathi Roll,Mixed Kathi Roll,Veg Kathi Roll,Cheese Kathi Roll,",
      "lastMileTravelString": 9.9,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/fonbo4i9ohdcteaqg8mp"
    },
    {
      "id": 29,
      "name": "Hyderabadi Biryani House",
      "cuisines": "Indian, Greek, Chinese",
      "rating": 4.8,
      "area": "Hollywood",
      "city": "Hyderabad",
      "avg_rating": 4.6,
      "menu": "Chicken Biryani,Mutton Biryani,Veg Biryani,Fish Biryani,Egg Biryani,Shrimp Biryani,Paneer Biryani,Dum Biryani,",
      "lastMileTravelString": 8.8,
      "image": "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/ucow7iwryvtcmim3ebki"
    }
  ]